FROM python:3.11-slim

WORKDIR /usr/src/app

COPY libs/ libs/

COPY tasks/gcpfetch/ gcpfetch/

WORKDIR /usr/src/app/gcpfetch

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "./gcp_fetch_main.py"]
