FROM node:16-slim


ENV REACT_APP_BACKEND_ADDRESS=https://agent-neo-backend-qaiojvs3da-uc.a.run.app
ENV REACT_APP_AUTH_DOMAIN=dev-o8s8b52y.auth0.com
ENV REACT_APP_AUTH_CALLBACK=https://agent-neo-react-fe-qaiojvs3da-uc.a.run.app/callback
ENV REACT_APP_AUTH_LOGOUT_URL=http%3A%2F%2Flocalhost:3000
ENV REACT_APP_AUTH_METHOD=auth0

WORKDIR /app


COPY package*.json ./


RUN npm install


COPY . .


RUN npm install -g serve


RUN npm run build


EXPOSE 8080


CMD ["serve", "-s", "build", "-l", "8080"]
# CMD ["serve", "-s", "-l", "8080", "./build"]