FROM node:16-slim


ENV REACT_APP_BACKEND_ADDRESS="https://agent-neo-backend-qaiojvs3da-uc.a.run.app"


WORKDIR /app


COPY package*.json ./


RUN npm install


COPY . .


RUN npm run build


RUN npm install -g serve


EXPOSE 8080


CMD ["serve", "-s", "build", "-l", "8080"]