# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables
ENV GCP_SITEMAPS_BUCKET=agent-neo4j-sitemaps
ENV GCP_PRACTITIONERS_GUIDE_SITES_BUCKET=agent-neo4j-practitionersguides
ENV GCP_OTHER_ARTICLES_BUCKET=agent-neo4j-otherarticles
ENV PYTHONPATH=/app/python_modules
ENV GCP_SERVICE_ACCOUNT_KEY_PATH=/app/gcp_service_account.json
ENV GITHUB_TOKEN=/app/github_token.json

# Install system dependencies for libmagic
RUN apt-get update && \
    apt-get install -y libmagic1 && \
    rm -rf /var/lib/apt/lists/*

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run main.py when the container launches
CMD ["python", "main.py"]