# app/Dockerfile

FROM python:3.11-slim

WORKDIR /app

COPY . .

# --- GEOS REQUIREMENT ---
RUN apt-get update
RUN apt-get install -y libgeos-dev
# --- END GEOS ---

RUN pip install -U pip
RUN pip3 install -r requirements.txt

ENV PORT=8080

# HEALTHCHECK CMD curl --fail http://localhost:8080/_stcore/health
RUN find /usr/local/lib/python3.11/site-packages/streamlit -type f \( -iname \*.py -o -iname \*.js \) -print0 | xargs -0 sed -i 's/healthz/health-check/g'

CMD streamlit run --server.port 8080 --browser.serverAddress 0.0.0.0 --server.enableCORS False --server.enableXsrfProtection False app.py
# CMD streamlit run app.py --server.port=${PORT}  --browser.serverAddress="0.0.0.0"