FROM python:3.11-slim

WORKDIR /usr/src/app

# Install Git
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY ../../libs libs/

WORKDIR /usr/src/app/

COPY tasks/githubfetch/requirements.txt .

COPY tasks/githubfetch/github_fetch_main.py .

WORKDIR /usr/src/app/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "./github_fetch_main.py"]










