# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the 'libs' directory into the container
COPY libs/ libs/

# Copy the contents of 'tasks/gcpfetch' directory into the container
COPY tasks/gcpfetch/ gcpfetch/

# Set the working directory to the 'gcpfetch' directory inside the container
WORKDIR /usr/src/app/gcpfetch

# Install any needed packages specified in 'requirements.txt'
RUN pip install --no-cache-dir -r requirements.txt

# Run 'main.py' when the container launches
CMD ["python", "./main.py"]
