# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the 'fetcher' module from the parent directory into the container
COPY ../fetcher/ .

# Copy 'main.py' and 'requirements.txt' from the current directory into the container
COPY main.py .
COPY requirements.txt .

# Install any needed packages specified in 'requirements.txt'
RUN pip install --no-cache-dir -r requirements.txt

# Run 'main.py' when the container launches
CMD ["python", "./main.py"]
